import { useState, useMemo } from 'react';
import {
  useJournalSessions, useJournalMilestones, useJournalSummary,
  useJournalRecommendations, useJournalAllMilestones,
} from '../hooks/useApi';
import { aggregateTargets } from '../utils/aggregate';
import { STATUS_COLORS } from '../utils/constants';
import MilestoneCard from '../components/MilestoneCard';
import AttemptCard from '../components/AttemptCard';
import MarkdownBlock from '../components/MarkdownBlock';
import styles from './Journal.module.css';

type Tab = 'milestones' | 'targets';

export default function Journal() {
  const { data: sessions } = useJournalSessions();
  const [activeSession, setActiveSession] = useState('');
  const [tab, setTab] = useState<Tab>('milestones');

  // --- Milestones tab data (per-session) ---
  const currentSession = activeSession || (sessions?.length ? sessions[sessions.length - 1].id : '');
  const { data: milestones } = useJournalMilestones(currentSession);
  const { data: summaryData } = useJournalSummary(currentSession);
  const { data: recsData } = useJournalRecommendations(currentSession);

  // --- Targets tab data (cross-session) ---
  const { data: allMilestoneData } = useJournalAllMilestones();

  const allAggregated = useMemo(() => {
    if (!allMilestoneData?.length) return [];
    return aggregateTargets(allMilestoneData);
  }, [allMilestoneData]);

  const hasAnySessions = !!sessions?.length;
  const currentMeta = sessions?.find(s => s.id === currentSession);
  const hasSessionContent = currentMeta?.hasMilestones || currentMeta?.hasSummary || currentMeta?.hasRecommendations;

  if (!hasAnySessions && !allMilestoneData?.length) {
    return (
      <div className={styles.empty}>
        <p><strong>No review sessions yet.</strong></p>
        <p>Journal data is generated by the review agent after each prover iteration.</p>
        <p>Make sure <code>archon-loop.sh</code> is running without <code>--no-review</code>, or run <code>./review.sh /path/to/project</code> manually.</p>
      </div>
    );
  }

  return (
    <div className={styles.root}>
      {/* Top-level tabs: Milestones (per-session) | Targets (global) */}
      <div className={styles.tabs}>
        <button className={`${styles.tab} ${tab === 'milestones' ? styles.tabActive : ''}`} onClick={() => setTab('milestones')}>Milestones</button>
        <button className={`${styles.tab} ${tab === 'targets' ? styles.tabActive : ''}`} onClick={() => setTab('targets')}>Targets</button>
      </div>

      {/* ── Milestones tab ── */}
      {tab === 'milestones' && (
        <div className={styles.content}>
          {/* Session selector */}
          {hasAnySessions && (
            <div className={styles.sessionBar}>
              {sessions!.map(s => (
                <button key={s.id}
                  className={`${styles.sessionBtn} ${(currentSession === s.id) ? styles.sessionBtnActive : ''}`}
                  onClick={() => setActiveSession(s.id)}>
                  {s.id.replace('session_', 'Session #')}
                  {!s.hasMilestones && !s.hasSummary && <span style={{ opacity: 0.4 }}> ○</span>}
                </button>
              ))}
            </div>
          )}

          {!hasSessionContent && (
            <div className={styles.empty}>
              <p><strong>Session {currentSession.replace('session_', '#')} — waiting for review data</strong></p>
              <p>The review agent creates milestones, summary, and recommendations after analyzing prover results.</p>
            </div>
          )}

          {/* Milestones */}
          {milestones && milestones.length > 0 && (
            <div className={styles.section}>
              <div className={styles.sectionLabel}>Milestones</div>
              {milestones.map((m, i) => <MilestoneCard key={i} milestone={m} />)}
            </div>
          )}

          {/* Summary */}
          {summaryData?.content && (
            <div className={styles.section}>
              <div className={styles.sectionLabel}>Summary</div>
              <div className={styles.card}><MarkdownBlock content={summaryData.content} className={styles.markdown} /></div>
            </div>
          )}

          {/* Recommendations */}
          {recsData?.content && (
            <div className={styles.section}>
              <div className={styles.sectionLabel}>Recommendations</div>
              <div className={styles.card}><MarkdownBlock content={recsData.content} className={styles.markdown} /></div>
            </div>
          )}
        </div>
      )}

      {/* ── Targets tab (global, independent of session selection) ── */}
      {tab === 'targets' && (
        <div className={styles.content}>
          {allAggregated.length === 0 && (
            <div className={styles.empty}>No targets found across any session</div>
          )}
          {allAggregated.map((t, i) => (
            <div key={i} className={styles.targetCard} style={{ borderLeftColor: STATUS_COLORS[t.status] || 'var(--border)' }}>
              <div className={styles.targetHeader}>
                <code className={styles.targetFile}>{t.file}</code>
                <span className={styles.targetTheorem}>{t.theorem}</span>
                <span className={styles.badge} style={{ color: STATUS_COLORS[t.status] }}>{t.status}</span>
              </div>
              <div className={styles.targetMeta}>
                {t.sessions.length} session{t.sessions.length > 1 ? 's' : ''} · {t.totalAttempts} attempt{t.totalAttempts !== 1 ? 's' : ''}
                {t.sessions.length > 1 && (
                  <span className={styles.sessionFlow}>
                    {t.sessions.map(s => s.replace('session_', '#')).join(' → ')}
                  </span>
                )}
              </div>
              {t.milestones.map((m, mi) => (
                <div key={mi}>
                  {t.sessions.length > 1 && (
                    <div className={styles.sessionTag}>
                      {(m as any).sessionId?.replace('session_', '#') || `#${mi + 1}`}
                      {' · '}
                      <span style={{ color: STATUS_COLORS[m.status] }}>{m.status}</span>
                    </div>
                  )}
                  {m.attempts && m.attempts.length > 0 && (
                    <div className={styles.attempts}>
                      {m.attempts.map((att, ai) => <AttemptCard key={ai} att={att} />)}
                    </div>
                  )}
                </div>
              ))}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
